services:
  - type: web
    name: lotto-web-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 127.0.0.1 --port 8000
    envVars:
      - key: PORT
        value: 8000
